/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'ASFS_app' 
 * Target:  'SX1261MB2BAS' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32l4xx.h"



#endif /* RTE_COMPONENTS_H */
